const REGULAR_BUILDER_BODY = [WORK, WORK, WORK, MOVE, CARRY];
const REGULAR_UPGRADER_BODY = [WORK, WORK, WORK, MOVE, CARRY, CARRY];
const REGULAR_HARVESTER_BODY = [WORK, WORK, WORK, MOVE, CARRY];
const REGULAR_TRANSPORT_BODY = [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY];

const START_HARVESTER_BODY = [WORK, WORK, MOVE, CARRY];

const EXPLORER_TRANSPORT_BODY = [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY];
const EXPLORER_BUILDER_BODY = [WORK, WORK, WORK, MOVE, MOVE, MOVE, CARRY, CARRY];
const EXPLORER_HARVESTER_BODY = [WORK, WORK, WORK, WORK, WORK, MOVE, CARRY];

module.exports = {REGULAR_BUILDER_BODY, REGULAR_HARVESTER_BODY, REGULAR_UPGRADER_BODY,
    REGULAR_TRANSPORT_BODY, START_HARVESTER_BODY, EXPLORER_BUILDER_BODY, EXPLORER_TRANSPORT_BODY,
    EXPLORER_HARVESTER_BODY};
