const REGULAR_BUILDER_BODY = [WORK, WORK, WORK, MOVE, CARRY];
const REGULAR_UPGRADER_BODY = [WORK, WORK, WORK, WORK, MOVE, MOVE, CARRY, CARRY, CARRY];
const REGULAR_HARVESTER_BODY = [WORK, WORK, WORK, MOVE, CARRY];
const REGULAR_TRANSPORT_BODY = [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY];

const REGULAR_MILLI_ATTACKER = [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                                TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                                TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                                ATTACK, ATTACK, ATTACK, ATTACK, ATTACK];

const REGULAR_RANGE_ATTACKER = [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                                TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                                RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK];

const START_HARVESTER_BODY = [WORK, WORK, MOVE, CARRY];

const EXPLORER_TRANSPORT_BODY = [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY];
const EXPLORER_BUILDER_BODY = [WORK, WORK, WORK, MOVE, MOVE, MOVE, CARRY, CARRY];
const EXPLORER_HARVESTER_BODY = [WORK, WORK, WORK, WORK, WORK, MOVE, CARRY];

module.exports = {REGULAR_BUILDER_BODY, REGULAR_HARVESTER_BODY, REGULAR_UPGRADER_BODY,
    REGULAR_TRANSPORT_BODY, START_HARVESTER_BODY, EXPLORER_BUILDER_BODY, EXPLORER_TRANSPORT_BODY,
    EXPLORER_HARVESTER_BODY, REGULAR_RANGE_ATTACKER, REGULAR_MILLI_ATTACKER};
