const REGULAR_BUILDER_BODY = [WORK, WORK, WORK, MOVE, CARRY];
const REGULAR_UPGRADER_BODY = [WORK, WORK, WORK, MOVE, CARRY, CARRY];
const REGULAR_HARVESTER_BODY = [WORK, WORK, WORK, MOVE, CARRY];
const REGULAR_TRANSPORT_BODY = [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY];

const START_HARVESTER_BODY = [WORK, WORK, MOVE, CARRY];


module.exports = {REGULAR_BUILDER_BODY, REGULAR_HARVESTER_BODY, REGULAR_UPGRADER_BODY,
    REGULAR_TRANSPORT_BODY, START_HARVESTER_BODY};
